# NumPy

### Jana Rusrus

<hr>

Python offers many libraries to work with, One of which is  NumPy. Here you will learn how Numpy supports large amounts of data, which come in handy later!

## Introduction to NumPy

NumPy stands for Numerical Python and it's a fundamental package for scientific computing in Python. NumPy provides Python with an extensive math library capable of performing numerical computations effectively and efficiently. This tutorial is intended as a basic overview of NumPy and introduces some of its most important
features.

<hr>

## Table of Contents


- Downloading Numpy

- NumPy versions

- NumPy Documentation

- Why use NumPy?

- How to create multidimensional NumPy arrays using various methods


- How to access and change elements in ndarrays


- How to load and save ndarrays


-  How to use slicing to select or change subsets of an ndarray 


- Understand the difference between a view and a copy of ndarray


- How to use Boolean indexing and set operations to select or change subsets of an ndarray


-  How to sort ndarrays


-  How to perform element-wise operations on ndarrays


-  Understand how NumPy uses broadcasting to perform operations on ndarrays of
different sizes.

<hr>

## Downloading Numpy

NumPy is included with Anaconda. This is the method recommended by the NumPy project. Once you’ve got conda installed, you can run the install command for the libraries you’ll need:

conda install numpy matplotlib

<hr>

## NumPy Versions

As with many Python packages, NumPy is updated from time to time. You can check which version of NumPy you have by typing !conda list numpy in your Jupyter Notebook or by typing conda list numpy in the Anaconda prompt. You can update your version by typing conda install numpy="the version you want" in the Anaconda prompt. As newer versions of NumPy are released, some functions may
become obsolete or replaced, so make sure you have the correct NumPy version before running the code. This will guarantee your code will run smoothly.

<hr>

## NumPy Documentation

NumPy is a remarkable math library and it has many functions and features. In this tutorial, I will only scratch the surface of what NumPy can do. If you want to learn more about NumPy, make sure you check out the NumPy Documentation:

- Numpy manual

<hr>

## Why use Numpy?

Numpy is built on top of the programming language C which works at a lower level on our computers. 
At the core of Numpy, it is an N-dimensional array object. This is just a multi-dimensional array that holds a group of elements with the same data type. Making arrays only able to handle all the elements with the same data type at a time, helps Numpy make quick computations. Here is a simple example that demonstrates this:

In [ ]:
# Using Python
import numpy as np 
import time
x = np.random.random(100000000)
start = time.time()
sum(x)/len(x)
print(time.time() - start)

9.429826498031616


In [ ]:
# Using Numpy
import numpy as np 
import time
x = np.random.random(100000000)
start = time.time()
np.mean(x)
print(time.time() - start)

0.06537890434265137


 We want to compare the time it takes to calculate the mean of this array using Python vs Numpy:

First, we imported numpy with the standard alise np. Using the time package we can check how long this code takes.
 In line 4, we  generate an array with a 100000000 floats between 0 and 1
 In Python, we find the sum of x and then divide it by the length of x, while we use np.mean() in NumPy

 After we run both codes, we note that it takes 9 seconds in Python. It makes sense that it takes a while with a hundred million value. 
However, it was much faster using NumPy, only 0.068 seconds!
Imagine how much the speed of the process is for more complex situations!

<hr>

##  Creating Numpy ndarrays

 Generally, there are two ways to create Numpy arrays. First, using the Numpy array function to create them from other arrays like objects such as regular array python list, and second, using a variety of built-in Numpy functions that quickly generate specific types of arrays. In this section, we start with the first way. 

 Here, we create our first array. It is a one-dimensional array that contains integers. Let's print the array that we just created as well as the type.

In [ ]:
import numpy as np 
x = np.array([1,2,3,4,5])
print(x)
print(type(x))
x.dtype

[1 2 3 4 5]
<class 'numpy.ndarray'>


dtype('int64')


 Note that the dtype is diffrent than the data type of the array. dtype returns the type of the elements of the array.

 Another useful attribute is shape. This returns the tuple of N that specifies the size of each dimension.
 if you have an array of a two-dimensional array, this tupel will return 2 values. One for the number of rows and one for the number of columns. 

In [ ]:
import numpy as np
y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y.shape

(4, 3)

The shape returns 4 which is the number of rows and 3 which is the number of columns. 

In [ ]:
y.size

12

The size attribute gives us the total number of elements in y which is 12.

Remember that, unlike Python lists, NumPy arrays must contain elements of the same type. Let's try an example with mixed data type using integers and floats. 

In [ ]:
x =np.array([1,2.5,4])
print(x,x.dtype)

[1.  2.5 4. ] float64


We note that when we input a list with both integers and floats, numpy assigns all elements to float64 dtype. This is called upcasting.

Numpy also allows you to specify a particular dtype you want to assign to an array:

In [ ]:
x = np.array([1.5,2.2, 3.7], dtype=np.int64)
print(x)
print('dtype:',x.dtype)

[1 2 3]
dtype: int64


Specifying the dtype can be useful in cases when you don't want to choose the wrong data type accidentally, or when you want to use a certain amount of precision in your calculations and want to save memory.

NumPy provides a way to save the arrays you created into a file for later use.

In [ ]:
x = np.array([1,2,3,4,5])
np.save('my_array',x)

This saves the array into a file called my_array.npy

You can load the array and use it later like this :

In [ ]:
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]


<hr>

## Using Built-in Functions to Create Ndarrays

Now, let's generate a NumPy array without using Python lists. Let's start by creating a NumPy array of zeros with a shape that we specify. We can do this by using NumPy zeros function:

In [ ]:
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
print('dtype:', x.dtype)

dtype: float64


This function takes as an argument the shape that you want to create. Passing in the tuple 3,4. gives us a 3*4 array of zeros. By default, this gives an array of float 64. We can change this by the keyword dtype.

In [ ]:
x = np.zeros((3,4),dtype=int)
print('dtype:',x.dtype)

dtype: int64


We can create an array filled with any constant values, using the full function:

In [ ]:
x= np.full((4,3),5)
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


This takes two arguments, the shape of the array and the constant that you want to fill it with

A fundamental array in linear algebra is the identity matrix, which is a square matrix that has ones along its main diagonal and zeros everywhere else. NumPy's eye function can be used to create this:

In [ ]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Since all identity matrix has a square shape, this only takes a single argument.

We can also use NumPy's diag function to create a diagonal matrix.

In [ ]:
x = np.diag([10,20,30,50])
print(x)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


This function takes the arguments, fill it in the diagonal, and fills in the rest with zeros. 

NumPy also has a useful function to generate arrays to generate arrays with specific numerical ranges. One useful one is arange, which creates an array with evenly spaced values within the given interval. It takes 3 arguments: start, stop, and step.

When arange has only one argument, it uses it as a stop argument and generates an array with integers from zero to that integer -1.

In [ ]:
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


When we use 2 arguments the first is the start argument and the second is the stop. The start is inclusive and the stop is exclusive.

In [ ]:
x=np.arange(4,10)
print(x)

[4 5 6 7 8 9]


When we use the three arguments, it generates an array starting from the first argument to the second -1 evenly spaced by the third.

In [ ]:
x=np.arange(1,14,3)
print(x)

[ 1  4  7 10 13]


Even though the arange function allows to use of non-integer steps, the output is usually inconsistent due to finite floating-point precision. For this reason, when we want a non-integer step, it is usually better to use a different NumPy function:linspace. It takes 3 arguments: start, stop, and n. Both start and stop being inclusive.

In [ ]:
x= np.linspace(0,25,10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


You can set the stop to exclusive by setting an endpoint to False.

In [ ]:
x= np.linspace(0,25,10,endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


We can use arange and linspace to create a rank2 array of any shape by combining them with the reshape function. This function converts to any specified shape. 

In [ ]:
x=np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
x= np.reshape(x,(4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Let's now create an array of randoms between 0 and 1 .

The following function is contained in the random module. So we type np. module to access this module and .random to access the function in that module.

NumPy also allows us to create NumPy arrays that contain random integers within a particular interval. The radiant function takes 3 arguments: the lower bound(inclusive), the upper bound(exclusive), and the shape.

The function np.random.normal(), creates an array with a given shape that contains a random number picked from a normal distribution within a given mean and a standard deviation

In [ ]:
x=np.random.randint(4,15,(3,2))
print(x)

[[14  9]
 [11  5]
 [12  5]]


In some cases, we may need to create a random array with some statistical properties. For example, we may want the random number of the array to have an average of zero.

In [ ]:
x=np.random.normal(0,0.1,size=(1000,1000))
print(x)

[[ 1.10645312e-01 -1.45338655e-01 -8.87019925e-02 ...  2.17092218e-01
  -6.46800826e-02  1.69317491e-01]
 [-1.25286326e-01  1.19814886e-01 -2.61209788e-01 ...  5.11652590e-02
  -9.38996971e-02  3.44514937e-03]
 [ 1.20286652e-01  8.28767131e-02  6.43957585e-02 ...  4.98709620e-02
  -2.18198575e-01 -1.30284201e-02]
 ...
 [ 2.78027488e-02 -6.60121031e-02  1.43668232e-01 ...  6.82511831e-03
   3.61561977e-02 -1.30048635e-01]
 [-8.16626065e-02 -3.01544598e-05 -1.13598321e-01 ... -3.25661232e-02
   1.70531444e-02  1.18771204e-01]
 [-7.03485809e-02 -1.67520950e-01 -1.46292132e-01 ... -5.75779427e-03
  -7.33241796e-02 -2.21539069e-02]]


This creates a a one-thousand by one thousand array of random floats drawn from a normal distribution with a mean of zero and a std of 0.1.

In [ ]:
print('mean:',np.mean(x))
print('std:',np.std(x))
print('max:',np.max(x))
print('min:',np.min(x))

mean: -8.418345450675405e-05
std: 0.10008570270981881
max: 0.5162056942900785
min: -0.5101727527377884


As we can see the the mean is very close to zero, and the std is very close to 0.1. Both the max and the mix of x are symmetric about zero.

<hr>

## Accessing, Deleting, and Inserting Elements Into ndarrays

Now that we know how to create a variety of NumPy arrays, let's see how NumPy allows us to manipulate the data within them.

NumPy arrays are mutable, meaning the data in them can be changed after we create it. It also can be sliced in many diffrent ways. This allows us to achieve any subset of the array that we want. We often use slicing to separate data. For example, when dividing the dataset into training, validating, and testing datasets.

We will start by looking at how the elements of the NumPy array can be accessed or modified by indexing.

In [ ]:
x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


Elements can be accessed by specifying their position using indexes inside square brackets 

In [ ]:
print('1st element:',x[0])
print('5th element:', x[4])


1st element: 1
5th element: 5


Positive indexes are used to specify positions from the beginning of the array.  We can also use negative indexes to specify positions from the end of the array.

In [ ]:
print('1st element:',x[-5])
print('5th element:', x[-1])


1st element: 1
5th element: 5


Notice that the same element can be accessed using both positive and negative integers. 

Now, let's see how we can modify the element of the array. We can do this by accessing the element in the array and then reassigning it.

In [ ]:
x[3] = 20
print (x)

[ 1  2  3 20  5]


We changed the fourth element from 4 to 20. 

Let's see how we can do this in the rank 2 array. 

Here is a 3 *3 array from 1 to 9

In [ ]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Let's access some elements in the array :

In [ ]:
print('element at(0,0):',x[0,0])
print('element at(0,1):',x[0,1])
print('element at(2,2):',x[2,2])

element at(0,0): 1
element at(0,1): 2
element at(2,2): 9


Elements in rank 2 array can be modified in the same way. We can change the element at 0,0 from 1 to 20 like this:

In [ ]:
x[0,0] = 20
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


Now let's take a look at how to add and delete elements. We can delete elements using NumPy's delete function. Let's see some examples. 

We can delete the first and last element like this:

In [ ]:
x=np.array([1,2,3,4,5])
print(x)

x = np.delete(x,[0,4])
print(x)

[1 2 3 4 5]
[2 3 4]


And here is a rank 2 array, We can delete the first row and column of y like this:

In [ ]:
y = np.arange(1,10).reshape(3,3)
print(y)

w = np.delete(y,0,axis=0)
print('\n',w)

v = np.delete(y,0,axis=1)
print('\n',v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2 3]
 [5 6]
 [8 9]]


We can add values to the array using the append function. 

In [ ]:
x = np.array([1,2,3,4,5])
print(x)



[1 2 3 4 5]


We can append an element 6 to the array like this:

In [ ]:
x = np.append(x,6)
print(x)

[1 2 3 4 5 6]


And we can append several elements to the array, like this:

In [ ]:
x= np.append(x,[7,8])
print(x)

[1 2 3 4 5 6 7 8]


In a rank 2 array, we can append a row containing 10,11,12 like this:

In [ ]:
w = np.append(y,[[10,11,12]],axis =0)
print(w)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


And we can append a new column like this:

In [ ]:
v = np.append(y,[[10],[11],[12]], axis=1)
print(v)


[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


Notice that when appending new rows and columns to rank 2 NumPy arrays, the rows and columns must have the correct shape to match the shape of the array. 

Now let's see how we can insert values into NumPy arrays. We can use the insert function for this. It takes in the array, index, elements, and access. Let's see an example 

In [ ]:
x = np.array([1,2,5,6,7])
print(x)


[1 2 5 6 7]


We can insert the integers( 3 and 4) between the elements (3 and 5) like this:

In [ ]:
x = np.insert(x, 2, [3,4])
print(x)

[1 2 3 4 5 6 7]


In [ ]:
y = np.array([[1,2,3],[7,8,9]])
print(y)


[[1 2 3]
 [7 8 9]]


In rank 2 array, we can insert a row between the first and last row like this:

In [ ]:
w = np.insert(y,1,[4,5,6],axis=0)
print(w)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


and insert a column like this:

In [ ]:
v= np.insert(y,1,5,axis=1)
print(v)

[[1 5 2 3]
 [7 5 8 9]]


NumPy also allows us to stack NumPy arrays on top of each other and side by side. The stack is done using vstack for verticle stacking or hstack function for horizontal stacking. It's important that to stack, the shape of the arrays must match. 

In [ ]:
x = np.array([1,2])
print(x)

[1 2]


In [ ]:
y = np.array([[3,4],[5,6]])
print(y)

[[3 4]
 [5 6]]


We can stack x on top of y, with vstack like this:

In [ ]:
z = np.vstack((x,y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


and we can stack  x to the right of y using hstack like this:

In [ ]:
w = np.hstack((y,x.reshape(2,1)))
print(w)

[[3 4 1]
 [5 6 2]]


<hr>

## Slicing ndarrays

In addition to accessing elements in the array one at a time, we can access a subset using slicing. Slicing is performed by combining indexes with a colon inside the brackets. In general, there are three ways of slicing:

1. ndarray[start: end] slicing from the starting index to the ending index

2. ndarray[start:] slicing from the starting index to the end of the array

3. ndarray[: end] slicing from the beginning of the array to the ending index

In the first and third methods the ending is always excluded, while in the second method, the ending is included.

NumPy array can be multidimensional, so when slicing, we usually have to specify the size of each dimension of the array. Let's see some examples of slicing with a rank 2 array.

Here is a 4*5 array, that contains integers from 1 to 20. We want to grab a subset from the array.

One way to do this is to use the part before the comma to define what indexes you want to grab from the rows and what you want from the columns after the comma. 

In [ ]:
x = np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
z = x[1:4,2:5]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


Here is another way that we can accomplish the same thing

In [ ]:
z=x[1:,2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [ ]:
z = x[:,2]
print(z)


[ 3  8 13 18]


This returns all the rows in column 2

It is important to note that the slice of x in z is not a copy of x. Rather x and z are two diffrent names for the same array. This means if you make any changes in z, you also change x. Let's see an example.

In [ ]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
z = x[1:,2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


Now let's change the last element in z to 555

In [ ]:
z[2,2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


Now if we print x, we can see that it is also being affected by this change

In [ ]:
print(x)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


If we want to create a new NumPy array that contains a copy of the values in the slice, we need to use NumPy's copy function. Let's repeat using the copy function:

In [ ]:
x= np.arange(20).reshape(4,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
z = x[1:,2:].copy()
print(z)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [ ]:
z[2,2] =555
print(z)

[[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]


In [ ]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


We can see that x has not been changed.

NumPy's diag function can extract the elements along the diagonal of the array

In [ ]:
z = np.diag(x)
print(z)

[ 0  6 12 18]


We can also print the elements above the main diagonal of the array, by setting a parameter k =1 

In [ ]:
z = np.diag(x,k=1)
print(z)

[ 1  7 13 19]


If k is a negative number, it will grab the values below the main diagonal

In [ ]:
z = np.diag(x,k=-1)
print(z)

[ 5 11 17]


By default, k is 0 which is why it grabs the main diagonal

<hr>

## Boolean Indexing, Set Operations, and Sorting

Up till now, we have seen how to make slices and select elements of a NumPy array using indexes. This is useful when we know the exact index of the element we want to select. However, there are many situations in which we do not know the indexes of the elements we want. For example, suppose we have 10000 * 10000 array of random integers ranging from 1 to 50000 and we only want to select integers that are less than 20. Boolean indexing can help in these cases by helping us select elements using logical arguments instead of explicit indexes. 

Let's see some examples:

consider this 5*5 array ranging from 0 to 24, we want to select elements greater than 10 using boolean indexing.

In [ ]:
x = np.arange(25).reshape(5,5)
print(x)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
print(x[x>10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


We use a boolean expression instead of indexes.

Let's also select elements that are less than or equal to 7:

In [ ]:
print(x[x<=7])


[0 1 2 3 4 5 6 7]


and now both that are greater than 7 and less than 17

In [ ]:
print(x[(x>10) & (x<17)])

[11 12 13 14 15 16]


We can use boolean indexing to assign the values to -1 

In [ ]:
x[(x>10) & (x<17)] = -1
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


We can create intersections, differences, and unions like this:

In [ ]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

print(np.intersect1d(x,y))

print(np.setdiff1d(x,y))

print(np.union1d(x,y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


We can also sort arrays in two ways using the function or using a method. However, there is a difference in sorting using a function that is out of place, meaning they do not change the original array. However when we use sort as a method. The array is sorted in place, meaning the original array is changed.

Let's create an unsorted array:

In [ ]:
x = np.random.randint(1,11, size=(10,))
print(x)

[ 9  1  8  3  4  3 10  3  3  8]


Sorting the elements using the function will sort the elements and keep the array as is

In [ ]:
print(np.sort(x))
print(x)

[ 1  3  3  3  3  4  8  8  9 10]
[ 9  1  8  3  4  3 10  3  3  8]


If we want to sort and keep only the unique function in it, we can combine it using the unique function like this:

In [ ]:
print(np.sort(np.unique(x)))

[ 1  3  4  8  9 10]


Now let's see how we can sort elements in place by using sort as a method:

Here is x again

In [ ]:
print(x)

[ 9  1  8  3  4  3 10  3  3  8]


In [ ]:
x.sort()
print(x)

[ 1  3  3  3  3  4  8  8  9 10]


We can see that affects the original x and sorts it.

When sorting rank 2 arrays, we need to tell the sort function whether we sort by rows or by columns. This is done by the keyword axis

Here is an unsorted rank 2 array:

In [ ]:
x = np.random.randint(1,11,size=(5,5))
print(x)

[[ 5  9 10  8  5]
 [ 4  8  5  7  5]
 [ 6  4  9  9  4]
 [ 4  8  7  8  3]
 [ 4  9  2  9  9]]


In [ ]:
print(np.sort(x,axis=0))

[[ 4  4  2  7  3]
 [ 4  8  5  8  4]
 [ 4  8  7  8  5]
 [ 5  9  9  9  5]
 [ 6  9 10  9  9]]


Here we sorted x by rows. Or we can sort x by columns like this:

In [ ]:
print(np.sort(x,axis=1))

[[ 5  5  8  9 10]
 [ 4  5  5  7  8]
 [ 4  4  6  9  9]
 [ 3  4  7  8  8]
 [ 2  4  9  9  9]]


<hr>

## Arithmetic operations and Broadcast

NumPy allows element-wise operations as well as matrix operations. In this section, we will only look at element-wise operations.

We can perform arithmetic operations using symbols or functions.

In [ ]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [ ]:
print(x+y)
print(np.add(x,y))

[ 6  8 10 12]
[ 6  8 10 12]


In [ ]:
print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))

[-4 -4 -4 -4]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [ ]:
print(np.sqrt(x))
print(np.exp(x))


[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In order to complete these operations, NumPy sometimes used something called broadcasting. Broadcasting is a term used to describe how NumPy handles arithmetic operations with arrays of different shapes. An important thing to note is that, because we are doing element-wise operations arrays that we are operating on must have the same shape or be broadcastable. 

Let's perform the same element-wise arithmetic operations on rank 2 arrays. Here are 2*2 matrixes. Let's do the same mathematical operations using simple notations. We can also apply mathematical functions such as square root to all the elements of the array at once. 

In [ ]:
x = np.array([1,2,3,4]).reshape(2,2)
y = np.array([5,6,7,8]).reshape(2,2)

print(x)
print(y)

print(x+y)

print(x-y)

print(x*y)

print(x/y)



[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Another great function of NumPy is statistical functions. Statical functions like mean provide us with statistical information about the elements in an array. Let's see some examples. 

We can calculate the average of the matrix like this 

In [ ]:
print('average of all:', np.mean(x))

average of all: 2.5


As well as the mean of individual rows and columns

In [ ]:
print('average of rows:', np.mean(x, axis=1))

print('average of columns:', np.mean(x, axis=0))

average of rows: [1.5 3.5]
average of columns: [2. 3.]


In [ ]:
x.std()

1.118033988749895

In [ ]:
np.median(x)

2.5

In [ ]:
x.max()


4

In [ ]:

x.min()

1

Now let's see how NumPy adds a single element to all elements in the array:

In [ ]:
print(x)
print(x+3)

[[1 2]
 [3 4]]
[[4 5]
 [6 7]]


In the examples above, NumPy is ready behind the scenes to broadcast 3 along the x array so that they have the same shape. This allows us to add 3 to each element of x in just one line of code. 

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=f938eb68-a4a9-4a86-9c1a-a86960266c01' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>